### Register a New User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Augustine",
  "email": "augustine@example.com",
  "password": "augustine023",
  "location": {
    "type": "Point",
    "coordinates": [40.7128, -74.0060]
  },
  "preferences": ["music", "sports"]
}

###

### Login a User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "augustine@example.com",
  "password": "augustine023"
}

###

### Get All Users
GET http://localhost:5000/api/users
Authorization: Bearer <jwt_token>


### Get a Single User by ID
GET http://localhost:5000/api/users/Id
Authorization: Bearer <jwt_token>


### Update a User
PUT http://localhost:5000/api/users/Id
Content-Type: application/json
Authorization: Bearer <jwt_token>

{
  "name": "deborah Updated",
  "preferences": ["movies", "travel"]
}


### Delete a User
DELETE http://localhost:5000/api/users/Id
Authorization: Bearer <jwt_token>



### Create a new event
POST http://localhost:5000/api/events
Content-Type: application/json
Authorization: Bearer <jwt_token>

{
  "name": "Tech Conference",
  "description": "A conference on AI & ML",
  "latitude": 12.9716,
  "longitude": 77.5946,
  "date": "2025-05-10T10:00:00Z",
  "categories": "Technology"
}

### Get All events
GET http://localhost:5000/api/events
Authorization: Bearer 

###

### Get a Single event by ID
GET http://localhost:5000/api/events/
Authorization: Bearer <jwt_token>

###

### Update an event
PUT http://localhost:5000/api/events/id
Content-Type: application/json
Authorization: Bearer <jwt_token>

{
  "message": "Updated notification message",
  "isRead": true
}

###

### Delete an event
DELETE http://localhost:5000/api/events/id
Authorization: Bearer <jwt_token>


### Create a new notification
POST http://localhost:5000/api/notifications
Content-Type: application/json
Authorization: Bearer <jwt_token>

{
  "message": "This is a notification message",
  "eventId": 123
}

###

### Get All notifications
GET http://localhost:5000/api/notifications
Authorization: Bearer <jwt_token>

###

### Get a Single notification by ID
GET http://localhost:5000/api/notifications/Id
Authorization: Bearer <jwt_token>

###

### Update a notification
PUT http://localhost:5000/api/notifications/Id
Content-Type: application/json
Authorization: Bearer <jwt_token>

{
  "message": "Updated notification message",
  "isRead": true
}

###

### Delete a notification
DELETE http://localhost:5000/api/notifications/Id
Authorization: Bearer <jwt_token>
